### 90-803 Machine Learning Foundations
#### Spring 2025
#### Lab 05: my_confusion_matrix

### Name: `Joanna Chang`
### AndrewID: `joannac2`

## Classifying the MNIST digits

#### First load the training and test set

In [3]:
%run read_all_data.py

In [4]:
X_train, y_train = read_all_image_label('train_images.txt', 'train_labels.txt')
X_test, y_test = read_all_image_label('test_images.txt', 'test_labels.txt')

In [4]:
(len(X_train), len(X_test))

(5000, 1000)

In [5]:
y_train[0]

5

In [6]:
X_train[0]

['                            ',
 '                            ',
 '                            ',
 '                            ',
 '                            ',
 '                +++++##+    ',
 '        +++++######+###+    ',
 '       +##########+++++     ',
 '        #######+##          ',
 '        +++###  ++          ',
 '           +#+              ',
 '           +#+              ',
 '            +#+             ',
 '            +##++           ',
 '             +###++         ',
 '              ++##++        ',
 '                +##+        ',
 '                 ###+       ',
 '              +++###        ',
 '            ++#####+        ',
 '          ++######+         ',
 '        ++######+           ',
 '       +######+             ',
 '    ++######+               ',
 '    +####++                 ',
 '                            ',
 '                            ',
 '                            ']

#### Convert Python lists to numpy arrays

In [7]:
import numpy as np
y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

In [8]:
img = X_train[0]

In [9]:
from pprint import pprint as pp
pp(img)

['                            ',
 '                            ',
 '                            ',
 '                            ',
 '                            ',
 '                +++++##+    ',
 '        +++++######+###+    ',
 '       +##########+++++     ',
 '        #######+##          ',
 '        +++###  ++          ',
 '           +#+              ',
 '           +#+              ',
 '            +#+             ',
 '            +##++           ',
 '             +###++         ',
 '              ++##++        ',
 '                +##+        ',
 '                 ###+       ',
 '              +++###        ',
 '            ++#####+        ',
 '          ++######+         ',
 '        ++######+           ',
 '       +######+             ',
 '    ++######+               ',
 '    +####++                 ',
 '                            ',
 '                            ',
 '                            ']


In [10]:
# encode a "digit" 

def char2num(c):
    if c==' ':
        n = 0
    elif c=='+':
        n = 1
    elif c=='#':
        n = 2
    else:
        print("!!!! This should not happen !!!")
    return n
        

In [11]:
[ char2num(c) for c in '+ ## ++']

[1, 0, 2, 2, 0, 1, 1]

In [12]:
s1 = ''.join(img)
s1

'                                                                                                                                                            +++++##+            +++++######+###+           +##########+++++             #######+##                  +++###  ++                     +#+                         +#+                          +#+                         +##++                        +###++                       ++##++                        +##+                         ###+                     +++###                    ++#####+                  ++######+                 ++######+                  +######+                 ++######+                   +####++                                                                                                     '

In [13]:
[ char2num(c) for c in s1];

In [14]:
def img2array(img):
    s = ''.join(img)
    fv = [char2num(c) for c in s]
    return fv

In [15]:
list(zip([1,2,3], [4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [16]:
X_train_np = [img2array(img) for img in X_train]
X_test_np = [img2array(img) for img  in X_test]

In [17]:
from sklearn.naive_bayes import GaussianNB
#from sklearn.neighbors import KNeighborsClassifier

In [18]:
model = GaussianNB()
#model = KNeighborsClassifier()

In [19]:
model.fit(X_train_np, y_train_np)
predicted = model.predict(X_test_np)
expected = y_test_np

In [20]:
# Import  metrics
from sklearn import metrics

# summarize the fit of the model

print(metrics.accuracy_score(expected, predicted))
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.509
              precision    recall  f1-score   support

           0       0.78      0.87      0.82        90
           1       0.58      0.98      0.73       108
           2       0.77      0.26      0.39       103
           3       0.64      0.27      0.38       100
           4       0.62      0.17      0.26       107
           5       0.50      0.08      0.13        92
           6       0.58      0.76      0.66        91
           7       0.77      0.25      0.38       106
           8       0.29      0.59      0.39       103
           9       0.38      0.89      0.53       100

    accuracy                           0.51      1000
   macro avg       0.59      0.51      0.47      1000
weighted avg       0.59      0.51      0.47      1000

[[ 78   0   0   0   1   1   4   0   6   0]
 [  0 106   0   0   0   0   1   0   1   0]
 [  4  11  27  10   3   0  27   1  19   1]
 [  3  13   1  27   0   1   6   2  37  10]
 [  3   3   2   1  18   1   6   0  22  51]
 [  9   8   2   1   

### TODO

Write `my_confusion_matrix` which works like the builtin `metrics.confusion_matrix`
 
1. Your implementation of `my_confusion_matrix` should be able to handle an arbitrary number of classes
2. While the builtin function returns a numpy array, your `my_confusion_matrix` should return 
a dataframe.  If you then did `df.values` you would get the same answer as the builtin routine
3. Similar to the builtin function, place the actuals on the rows and the predicted on the columns


In [28]:
import pandas as pd

def my_confusion_matrix(expected, predicted):
    unique_labels = sorted(set(expected) | set(predicted))
    matrix = pd.DataFrame(0, index=unique_labels, columns=unique_labels)

    for actual, pred in zip(expected, predicted):
        matrix.at[actual, pred] += 1

    return matrix

In [35]:
my_confusion_matrix(expected, predicted)

Predicted   0    1   2   3   4  5   6   7   8   9
Actual                                           
0          78    0   0   0   1  1   4   0   6   0
1           0  106   0   0   0  0   1   0   1   0
2           4   11  27  10   3  0  27   1  19   1
3           3   13   1  27   0  1   6   2  37  10
4           3    3   2   1  18  1   6   0  22  51
5           9    8   2   1   1  7   3   0  51  10
6           0   11   2   0   1  2  69   0   6   0
7           0    8   0   2   2  2   1  27   3  61
8           2   21   1   1   2  0   1   2  61  12
9           1    3   0   0   1  0   0   3   3  89