### 90-803 Machine Learning Foundations
#### Spring 2025
#### Lab 04

### Name: `Joanna Chang`
### AndrewID: `joannac2`

## Classifying the MNIST digits

#### First load the training and test set

In [121]:
%run read_all_data.py

In [122]:
X_train, y_train = read_all_image_label('train_images.txt', 'train_labels.txt')
X_test, y_test = read_all_image_label('test_images.txt', 'test_labels.txt')

# it‘s going to train on 5000 images, and be tested on 1000 images


In [123]:
(len(X_train), len(X_test))

(5000, 1000)

In [124]:
X_train[0] #The image is a list

['                            ',
 '                            ',
 '                            ',
 '                            ',
 '                            ',
 '                +++++##+    ',
 '        +++++######+###+    ',
 '       +##########+++++     ',
 '        #######+##          ',
 '        +++###  ++          ',
 '           +#+              ',
 '           +#+              ',
 '            +#+             ',
 '            +##++           ',
 '             +###++         ',
 '              ++##++        ',
 '                +##+        ',
 '                 ###+       ',
 '              +++###        ',
 '            ++#####+        ',
 '          ++######+         ',
 '        ++######+           ',
 '       +######+             ',
 '    ++######+               ',
 '    +####++                 ',
 '                            ',
 '                            ',
 '                            ']

In [125]:
y_train[0]

5

#### Convert Python lists to numpy arrays

In [126]:
import numpy as np
y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

In [181]:
img = X_train[0]

In [182]:
len(img)

28

In [183]:
from pprint import pprint as pp
pp(img)

['                            ',
 '                            ',
 '                            ',
 '                            ',
 '                            ',
 '                +++++##+    ',
 '        +++++######+###+    ',
 '       +##########+++++     ',
 '        #######+##          ',
 '        +++###  ++          ',
 '           +#+              ',
 '           +#+              ',
 '            +#+             ',
 '            +##++           ',
 '             +###++         ',
 '              ++##++        ',
 '                +##+        ',
 '                 ###+       ',
 '              +++###        ',
 '            ++#####+        ',
 '          ++######+         ',
 '        ++######+           ',
 '       +######+             ',
 '    ++######+               ',
 '    +####++                 ',
 '                            ',
 '                            ',
 '                            ']


In [184]:
# encode a "digit", convert it to a number

def char2num(c):
    if c == ' ':
        n = 0
    elif c == '+':
        n = 1
    elif c == '#':
        n = 2
    else:
        print("!!!! This should not happen")
    return n


In [185]:
[ char2num(c) for c in '+ ## ++']

[1, 0, 2, 2, 0, 1, 1]

In [187]:
s1 = ''.join(img) # join the list of strings into a single string

In [188]:
[ char2num(c) for c in s1]; # put the semi-colon to suppress the output

In [145]:
def img2array(img): # a list of strings to a vector of numbers
    return np.array([ char2num(c) for c in s1])

In [ ]:
list(zip([1,2,3], [4,5,6])) # zip two lists into a list of tuples

[(1, 4), (2, 5), (3, 6)]

In [135]:
X_train_np = [img2array(img) for img in X_train]
X_test_np = [img2array(img) for img  in X_test]

In [136]:
from sklearn.naive_bayes import GaussianNB
#from sklearn.neighbors import KNeighborsClassifier

In [137]:
model = GaussianNB()
#model = KNeighborsClassifier()

In [138]:
model.fit(X_train_np, y_train_np)
predicted = model.predict(X_test_np) # try it out one the prediction
expected = y_test_np

In [139]:
# Import  metrics
from sklearn import metrics

# summarize the fit of the model

print(metrics.accuracy_score(expected, predicted))
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.509
              precision    recall  f1-score   support

           0       0.78      0.87      0.82        90
           1       0.58      0.98      0.73       108
           2       0.77      0.26      0.39       103
           3       0.64      0.27      0.38       100
           4       0.62      0.17      0.26       107
           5       0.50      0.08      0.13        92
           6       0.58      0.76      0.66        91
           7       0.77      0.25      0.38       106
           8       0.29      0.59      0.39       103
           9       0.38      0.89      0.53       100

    accuracy                           0.51      1000
   macro avg       0.59      0.51      0.47      1000
weighted avg       0.59      0.51      0.47      1000

[[ 78   0   0   0   1   1   4   0   6   0]
 [  0 106   0   0   0   0   1   0   1   0]
 [  4  11  27  10   3   0  27   1  19   1]
 [  3  13   1  27   0   1   6   2  37  10]
 [  3   3   2   1  18   1   6   0  22  51]
 [  9   8   2   1   

In [4]:
my_confusion_matrix(expected, predicted) #.values

NameError: name 'my_confusion_matrix' is not defined

### TODO 3
Redfine img2array to include the class label and re-run the below code. Accuracy should be close to 0.986

In [248]:
def img2array(img, label):  # Include label as a parameter
    s1 = ''.join(img)  # Join list of strings into a single string
    img_array = np.array([char2num(c) for c in s1])  # Convert to numerical array
    return np.append(img_array, label)  # Append label to the array


In [249]:
list(zip([1,2,3], [4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [250]:
X_train_np = [img2array(img, label) for img, label in zip(X_train, y_train)]
X_test_np = [img2array(img, label) for img, label in zip(X_test, y_test)]

#### Put the actual lable into the model, then you can get pretty high accuracy

In [251]:
model = GaussianNB()

model.fit(X_train_np, y_train_np)
predicted = model.predict(X_test_np)
expected = y_test_np

print(metrics.accuracy_score(expected, predicted))
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.986
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        90
           1       1.00      0.98      0.99       108
           2       0.97      1.00      0.99       103
           3       0.98      0.99      0.99       100
           4       1.00      0.98      0.99       107
           5       0.98      0.99      0.98        92
           6       0.98      0.99      0.98        91
           7       0.97      0.97      0.97       106
           8       0.98      0.97      0.98       103
           9       1.00      1.00      1.00       100

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

[[ 89   0   1   0   0   0   0   0   0   0]
 [  0 106   2   0   0   0   0   0   0   0]
 [  0   0 103   0   0   0   0   0   0   0]
 [  0   0   0  99   0   1   0   0   0   0]
 [  0   0   0   2 105   0   0   0   0   0]
 [  0   0   0   0   